### ISSUE TITLE
add a posibility to dim screen more?

### ISSUE THREAD

**Issue by alpakeno** [devnoname120/vitabright#1]
Background screen get more dimmer when opening the notification icon ( the top righted icon in the corner of screen )
so can it be possible for vitabright to use that value?

**Comment by devnoname120** [comment]
Dimming the screen in a hardware manner (like I do) is different from applying a semi-transparent filter (like vFlux and the background when opening notifications). The later is not good for performances (unless done with a shader), and I suspect that the contrast is worse than with a hardware method.

It is definitely possible to lower the screen brightness even more than vitabright already does. I will continue reverse engineering at some point, and add this feature.

**Comment by devnoname120** [comment]
Version 0.5 allows you to provide your own brightness table. Each line corresponds to a brightness level. By changing the values, you should be able to figure out how to get a lower brightness.

**Comment by CelesteBlue-dev** [comment]
@devnoname120 please may you provide an exemple of config (for exemple the one you use).

**Comment by alpakeno** [comment]
@devnoname120 thanks a lot for updating this awesome plugin.
Is there any method or tool needed that can help getting the brightness table?

**Comment by Outpox** [comment]
@CelesteBlue-dev @alpakeno you should take a look at [this post](https://github.com/devnoname120/vitabright/issues/3#issuecomment-379305512) in which the author gives a config file for example.
