### ISSUE TITLE
Vitabright never works

### ISSUE THREAD

**Issue by 6436437Numbers** [devnoname120/vitabright#10]
Hello sir, I have the Vita 1000 OLED 3.60 Ensō and I installed your vitabright. It has no effect from what I can see. I downloaded the files(vitabright.skprx, vitabright_lut.txt) from the latest release 0.9 and put them in the ur0:/tai/ folder. There's no tai folder in ux0. I restart the vita and change the brightness levels. No effects at all.
This is my config.txt file
```
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/nonpdrm.skprx
ur0:/tai/vitabright.skprx
# henkaku.skprx is hard-coded to load and is not listed here
# main is a special titleid for SceShell
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
*main
ur0:tai/nolockscreen.suprx
ur0:tai/shellbat.suprx
ur0:tai/notrophymsg.suprx
ur0:tai/henkaku.suprx
```
I gone over the config and location many times. I wondered if I placed it wrong or entered a typo. I tried it with only the vitabright plugin by itself and no luck still. This should work so what else could be the problem? Please help.

**Comment by devnoname120** [comment]
Could you try transferring the plugin and `vitabright_lut.txt` via FTP (or USB if you used FTP)?

**Comment by 6436437Numbers** [comment]
FTP was the previous method. Following your suggestion, both the plugin and `vitabright_lut.txt` was transferred via USB. I restarted the vita to be certain and then changed the brightness setting by holding down the PS button. I saw zero changes from the default luminosity. It may not matter but when I tried the 0.1 version, there was a difference. I made no modification to the gamma table. The files are directly from the github release vitabright-0.9.zip. Every other plugin is working.

**Comment by devnoname120** [comment]
I'm sorry I don't have any ideas. If you have a working vitasdk install, I suggest you to:
- Compile it by doing `mkdir build && cd build && cmake .. -DENABLE_LOGGING=ON`.
- Transfer the compiled plugin to your Vita.
- Restart your Vita.
- Try to move the slider and stuff.
- Send here the log `ur0:data/vitabright_log.txt`.

**Comment by K4thos** [comment]
change this line in your config.txt:
ur0:/tai/vitabright.skprx
to this:
ur0:tai/vitabright.skprx

**Comment by devnoname120** [comment]
That shouldn't change anything.

**Comment by rafaelqueiroz89** [comment]
@devnoname120 i have the same problem, i will try your debugger and show you the log. I have henkaku and 3.60
