### ISSUE TITLE
Brightness change due to inactivity can do a 'jump'

### ISSUE THREAD

**Issue by devnoname120** [devnoname120/vitabright#11]
If the current brightness is lower than the brightness level for inactivity, the brightness will suddenly 'jump' when the vita is inactive.

Possible fix: ignore inactivity if the inactivity brightness is greater than the current brightness.

**Comment by unhawkable** [comment]
@devnoname120 thank you so much for adding support for vita 2000!!!

**Comment by thorry69** [comment]
hi, the first great job, one question, this pluggin, in my psvita 2000 don't work, put in tai ur0:/tai/, dont work can help me please, my vita downgrade with moduro, 3.70>3.60, no H-encoke, Enso ok,
