### ISSUE TITLE
Brightness not changing

### ISSUE THREAD

**Issue by WBSpitfire** [devnoname120/vitabright#15]
Model: 1101 3G OLED / 3.60 Enso
I installed the Vitabright plugin but noticed it wasn't working. Looking at the other issues, I noticed that there was a debug 1.0 version to get a log, and it is as follows:

> vitabright started...
> [OLED] brightness table parsing failure
> [LCD] getmodinfo: 0x9001002
> [LCD] modid:0x00011635

~~From reading this thread: https://github.com/devnoname120/vitabright/issues/13 , I saw that this is~~ ~~due to either incorrect formatting of the lut.txt or not having the unix line ending format.~~

~~However I have NOT modified the file that had come with the 1.0 download, so why is it failing?~~ ~~Seems odd it would fail to work with the file it comes with.~~

Files were transferred over FTP thru Vitashell's FTP. 

EDIT: Okay, so it looks like the culprit in this case was FileZilla, at least for the parsing failures. As it turns out, FileZilla likes to be helpful and do automatic line ending conversion when uploading files. Except, it was causing issues. So if anyone else is having this issue with FileZilla, change the transfer type from Auto to Binary, and it will not mess with it.

New log is as follows:

> vitabright started...
> [OLED] getmodninfo:0x00000000
> [OLED] modid:0x000100F7
> [OLED] Size ok, hooking....
> [OLED] injectdata: 0x00000000
> [LCD] getmodinfo: 0x9001002
> [LCD] modid:0x0001165F

That said, I still don't see a brightness difference from it being "working".

**Comment by devnoname120** [comment]
In this case it seems to be the same issue as https://github.com/devnoname120/vitabright/issues/13.
