### ISSUE TITLE
Doesnt work on My PS2000

### ISSUE THREAD

**Issue by LuanTeles** [devnoname120/vitabright#17]
I installed it right, rebooted

and the brightness doesnt increased at all, the slider is where i left it before the install.

But now the minimum value is way darker, i not have the yellow or other option sliding it even down.

but what buggs me the most is not beeing able to increase the brightness

**Comment by LuanTeles** [comment]
I forgot to mention I'm on 3.65 H-encore

**Comment by LuanTeles** [comment]
I saw some ppl with the same issues, maybe a diferente screen revision?

**Comment by devnoname120** [comment]
No yellow is normal (it's only for OLED screens), and screen getting darker is normal, that's the entire point of this plugin.
