### ISSUE TITLE
Fix 0.1 version?

### ISSUE THREAD

**Issue by revildaron** [devnoname120/vitabright#20]
I know some of psv 1000 doesnt work with vitabright so atleast can u fix  0.1 version because that only version work rn on it. Like fix brightness setting goes back to normal when screen on standby or put brightness setting on max without gamma table?

**Comment by Feardarks** [comment]
im waiting for this too. sucks that not works on every vita

**Comment by devnoname120** [comment]
I'm not interested in working on it. Feel free to do the changes.

**Comment by devnoname120** [comment]
Not needed anymore since https://github.com/devnoname120/vitabright/pull/28 adds support for remaining OLED models.
