### ISSUE TITLE
suggestion: a local vita app/overlay to modify the values on the fly?

### ISSUE THREAD

**Issue by QUAKEULUS** [devnoname120/vitabright#24]
Thank you for making this! This was exactly what I was looking for, some ps1 games via adrenaline are quite too dark

It would be immensely helpful for experimentation to have a shorter reiteration cycle between changing the values and seeing the results. Loading and saving as multiple config files for different games/scenarios would also be immensely helpful.

**Comment by devnoname120** [comment]
Hmm I can look into that, shouldn't be too hard.

**Comment by devnoname120** [comment]
OK so here you are: [vitabright-experiments.zip](https://github.com/devnoname120/vitabright/files/5705968/vitabright-experiments.zip)

**Instructions**:
- Remove your currently installed vitabright (and vitacompanion if you have).
- Install both plugins. Install them in `config.txt` as well.
- Get the IP of your vita (you can find it by pressing select in Vitashell).
- On a PC **on the same Wi-Fi network as your Vita**, you can use Filezilla or whatever you use to change the file `vitabright_lut.txt`. You can connect to FTP even if Vitashell is closed (that's the magic of vitacompanion).
- Open `cmd.exe`
- You can reload the vitabright config any time you want by running `nc 192.168.1.10 1338` and then writing `vitabright_reload`. So you can easily edit the gamma brightness table vita FTP and then reload it with the command.


@QUAKEULUS Let me know if you have any questions.

**Comment by devnoname120** [comment]
Also you might want to look at these explanations: https://github.com/devnoname120/vitabright/wiki/What-is-the-format-of-the-OLED-gamma-table%3F
One column on the image is one line in `vitabright_lut.txt`.

**Comment by devnoname120** [comment]
@QUAKEULUS I've created an app making it easier: https://github.com/devnoname120/vitabright-lut-editor/releases/latest
