### ISSUE TITLE
Please Enable A Method To Reset To Stock Default

### ISSUE THREAD

**Issue by MadZiontist** [devnoname120/vitabright#26]
I accidentally made undesirable permanent changes and now have no way to reset to factory stock. A reset option to factory default settings would be great. Another good feature would be a menu system, where the user could select from various lut table files stored on the Vita in a folder, and load them, previewing the changes.

**Comment by devnoname120** [comment]
I suggest replacing the lut file with the original one from the latest release.

**Comment by MadZiontist** [comment]
> 
> 
> I suggest replacing the lut file with the original one from the latest release.

Yeah I just sorted that out, thanks. But my suggestion still stands. I think a menu loading system, where different lut files can be loaded and and the changes previewed would be really cool. But that's kind of putting the cart before the horse. I think this plugin has a lot of potential. But the VPK configuration app is incredibly confusing and a clunky. It's really hard to discern what the diifferent images represent and what changes are made when values are adjusted. It really needs to be a lot more user friendly and intuitive. I respect this project which is why I'm taking the time to offer feedback, like you asked for.
