### ISSUE TITLE
Blue light filter on PS Vita 2000

### ISSUE THREAD

**Issue by MarcoDjallo** [devnoname120/vitabright#27]
Hello,

I just wanted to know if there's any possibility of obtaining a blue light filter (like f.lux) like the one you get by editing the gamma table on PS Vita 1000 also on the 2000's LCD screen.

I know there are plugins that do that, but their approach causes important FPS drops, making the games unplayable.

Thank you in each case and for all your work!

**Comment by devnoname120** [comment]
@MarcoDjallo I'm not sure whether it can be easily done just by interacting with the screen driver. Is there any blue light filter plugin using a shader? It should be pretty fast and not cause loss of performances.
