### ISSUE TITLE
>Causes Vita Lut Editor To Crash

### ISSUE THREAD

**Issue by MadZiontist** [devnoname120/vitabright#30]
> 
> 
> precompiled binary (with fix from PR#28):
> [vitabright.zip](https://github.com/devnoname120/vitabright/files/6366269/vitabright.zip

So far, so good...it's working on my PCH-1101. Previously the only version that worked was v0.01. This newer, fixed version works a lot better. Thanks @SKGleba!

_Originally posted by @MadZiontist in https://github.com/devnoname120/vitabright/issues/13#issuecomment-826328203_

**Comment by MadZiontist** [comment]
Vita Lut Editor crashes as soon as a launch is attempted.

**Comment by JhonnySalles** [comment]
I had the same crash problem in the previous version, but when replacing the skprx file, and then restarting it worked
