### ISSUE TITLE
A question from a large community in Russia.

### ISSUE THREAD

**Issue by Alexander-Shibanov** [devnoname120/vitabright#32]
Hello! We are very happy and thank you for your contribution to the development of PSV. 
**Help us please** (speaking on behalf of the community) 
I apologize for my English (I am writing via google translator)
In general. We install and run on PSV 1000. Everything works great, thank you very much !!!
But on PSV 2000 it works but not completely.

I explain: 
As I understand it(Vitabright), there is brightness above the maximum and brightness below the minimum.
On PSV 1000 it works both at maximum and at minimum. On PSV 2000 only works at minimum.
Is it possible to somehow achieve higher maximum brightness on PSV 2000?
Thank you for your attention, I look forward to your feedback. Good luck to you!

**Comment by devnoname120** [comment]
Hello, unfortunately it's not possible to increase the brightness further than the maximum on PSVita 2000 models.
