### ISSUE TITLE
My Improved Gamma Table

### ISSUE THREAD

**Issue by buzeak** [devnoname120/vitabright#36]
Here is my improved gamma table.

[vitabright_lut.txt](https://github.com/devnoname120/vitabright/files/8017996/vitabright_lut.txt)

It is designed to be a simple upgrade to the default brightness slider.

It has five extra bright custom values, including maximum capable brightness of the screen.

Then six values taken from the default slider, including default brightest, default darkest, and every third value between. (It divided up perfectly)

Then a darker custom value.

Then the even darker value taken from the default inactivity dim.

And finally three extra dark custom values, including the darkest before the screen loses its contrast.

My little contribution to this magical mod. I spent a few days on it, so it should be good. And I may improve it further later :-)

**Comment by buzeak** [comment]
This mod also works well with these three mods: 
NoPowerLimits.skprx (to use full brightness slider on all games)
nosleep.skprx (to disable sleep)
noled.skprx (to disable that annoying blue led in the PlayStation button on the front)

**Comment by devnoname120** [comment]
Thank you so much for sharing your LUT! I'll take a look later, and possibly release a new version.

**Comment by devnoname120** [comment]
@buzeak Please remind me if I don't give you an update within two weeks :)

**Comment by buzeak** [comment]
OK, and you may also want to add a warning that the higher brightness may cause the vita to crash because of the increased power consumption. Even the limited brightness applications are a little brighter than they would be originally.

The chance of crashing is still very small, but if you keep getting crashes, it's good to know that it's just the brightness.

So far mine has only crashed because I also removed the high power game brightness limit, and was playing a high speed rally game on maximum capable bright of the screen! x-)

**Comment by buzeak** [comment]
Hi again, just reminding you like you asked, that the vitabright update has not been done and it has been two weeks.

**Comment by devnoname120** [comment]
@buzeak Super busy last 2 weeks. Still top of my mind. Will get back to you in 1-2 weeks.

**Comment by devnoname120** [comment]
> I have been using a black to white gradient image that I added to the live lut editor, which I find to be the best, also a few reference images of gameplay. Do you want these to upgrade the lut editor too?

Yes! Could you open an issue with those images on the lut editor repo?

**Comment by buzeak** [comment]
I have now opened an issue on the lut editor repo with the images you requested. :+1:

**Comment by buzeak** [comment]
I see that you have now committed my first improved LUT table.
But my latest and best LUT file is attached to my 4th comment above.
Did you make a mistake?

**Comment by devnoname120** [comment]
@buzeak Here is the branch with your LUT improvements: https://github.com/devnoname120/vitabright/tree/oled-support-fix

I don't have my PS Vita with me so I can't test it. Can you confirm that this updated version works properly?
[vitabright-2.0b1.zip](https://github.com/devnoname120/vitabright/files/8218111/vitabright-2.0b1.zip)

**Comment by buzeak** [comment]
I have now tested it, and it does not work.

I unzipped the file in your comment,
Then I moved my working vitabright.skprx and vitabright_lut.txt out.
Then I moved the new vitabright.skprx and vitabright_lut.txt in.
Then I rebooted.
And now my vita bootloops, and I don't know how to fix it.

I have noticed that the new vitabright.skprx is 6,925 bytes.
And my working one that I just moved out is 4,289 bytes.

And that vitabright_lut.txt file is not my best, my best is here: 
[vitabright_lut.txt](https://github.com/devnoname120/vitabright/files/8218359/vitabright_lut.txt)



Do you have any advice on how to fix my vita bootloop problem?

You can see all what I did in this FileZilla log screenshot screenshot: 
![filezilla log screenshot](https://user-images.githubusercontent.com/70481224/157540857-ada328be-b7a7-4e71-92c4-0a573ff7fe9c.jpg)

**Comment by devnoname120** [comment]
@buzeak Thanks for your report. You can start your PS Vita holding the L trigger and it will boot without plugins enabled. You can then disable Vitabright and reboot. I'll figure out the issue once I get access to a PS Vita.

**Comment by buzeak** [comment]
Thank you. I have just retested it, and it is the new vitabright.skprx that does not work.
Good idea, it would be quicker to edit and test when you have a vita at hand.

**Comment by devnoname120** [comment]
@buzeak Can you test this new version?
[vitabright-2.0b2.zip](https://github.com/devnoname120/vitabright/files/8262865/vitabright-2.0b2.zip)

**Comment by buzeak** [comment]
I'll have it tested in 10 minutes.👍
________________________________

**Comment by buzeak** [comment]
It WORKS! :+1: 

I have double tested it with my latest: [vitabright_lut.txt](https://github.com/devnoname120/vitabright/files/8263025/vitabright_lut.txt) on my old original vita :-)

**Comment by devnoname120** [comment]
@buzeak Awesome! I really like your gamma table. The only ‶disappointment″ I have is that the minimum brightness level is now too high for me in the dark. I'm okay with trading less contrast for less eye-strain.

**Comment by buzeak** [comment]
@devnoname120 Are you sure you're using my latest gamma table? I think the darkest is darker than any before: 4D 48 5B EB DF EE EA C7 E9 F8 BA F3 00 00 00 00 00 00 00 00 00

Just let me know and I will make it go darker for you :-)

**Comment by devnoname120** [comment]
@buzeak I can confirm that I wasn't using the latest one. It's much better now. Your LUT is a huge step up and makes Vitabright much better. Thanks a lot!

Regarding the previous value it was:
https://github.com/devnoname120/vitabright/blob/fcb46b8d1141e813e5d00532b772710f6b55ddf8/oled/assets/vitabright_lut.txt#L18-L19

I'm not sure if it was more or less bright than your lowest brightness.

**Comment by devnoname120** [comment]
@buzeak By the way, isn't the previous maximum brightness even brighter than your new value?

https://github.com/devnoname120/vitabright/blob/fcb46b8d1141e813e5d00532b772710f6b55ddf8/oled/assets/vitabright_lut.txt#L2

**Comment by buzeak** [comment]
My dimmest is very very very similar to that one.
And the new maximum brightness is also very very very similar to that one, just balanced as you can see the E1 E1 FF at the start shows maximum blue (FF).

**Comment by buzeak** [comment]
@devnoname120 I have just made the dimmest even dimmer, so it's dark enough to play in the complete darkness. And as dim as my phone can go. I will give you the file as soon as I have finished adjusting the other brightnesses so that they step evenly.

**Comment by devnoname120** [comment]
@buzeak Great! Is the contrast still bearable?

**Comment by buzeak** [comment]
@devnoname120 Yes,👍 the colours are a little weaker, but they are well balanced and good enough.

**Comment by buzeak** [comment]
@devnoname120 I have now finished my 3rd (and hopefully final) lut file!

And here it is: [vitabright_lut.txt](https://github.com/devnoname120/vitabright/files/8289897/vitabright_lut.txt)

I have spent all day working on it, and I am very happy with it. :+1: 

It now has one less value from the default slider, and one less brighter custom value. So it now has two more custom values at the dimer end, giving seven custom values where it's needed!

It also now has the same default maximum brightest available on 444 mhz games, so there's no worry about it crashing on those games unless you also install the NoPowerLimits.skprx plugin like I have.

The brightness increments are smaller at the dark end, but they all step up nicely.

Enjoy! :-)

**Comment by devnoname120** [comment]
> unless you also install the NoPowerLimits.skprx plugin like I have

Turns out I recently disabled this limit directly in Vitabright. 😬 😬
https://github.com/devnoname120/vitabright/commit/19916c88ac0441813180b1767f498d693f520957

What's your opinion on this? Should I keep the limit or not?

**Comment by buzeak** [comment]
@devnoname120 I think that it 's very good that you removed the limit.👍 Just make sure that you warn everyone, because it does make my original vita crash on maximum maximum. And it would be really frustrating if you did not know the cause.🤔

**Comment by devnoname120** [comment]
@buzeak Another possibility would be to keep the limit, and let users download `NoPowerLimits.skprx` if they want to remove it (at their own risk). What would you think of this option?

I wonder how frequently the PS Vita crashes when above the limit. If it happens very frequently then it doesn't make sense to unlock the brightness anyway.

**Comment by buzeak** [comment]
@devnoname120 Vitabright is an overclock for applications that are not 444 mhz anyway. So they should be warned for just that reason alone.

I don't think that my vita will ever crash at just one brightness level down from maximum.

And it does not crash if I drive a slower car, or in the menus.

I think it will only crash when the CPU, GPU and screen are all at maximum. Lots of games don't use the GPU much, so I doubt it would crash on those games even with the limiter removed on maximum brightness.

If people really can't be warned, I guess you could keep the limiter on, and I could make the max limited brightness a little brighter.

Or maybe just remove the brightest value?

**Comment by buzeak** [comment]
@devnoname120 It would be ideal if you could move the limitor to disable just the brightest two settings for the Vita 1000.

And I do not know about the Vita 2000.

**Comment by devnoname120** [comment]
> It would be ideal if you could move the limitor to disable just the brightest two settings for the Vita 1000.

Actually this may be possible. I don't have a Vita with me but I'll build up a test version so that you can try it out. :)

**Comment by buzeak** [comment]
That would be great! And I would give it a poper test run. A good reason to do some proper gaming.😁

**Comment by devnoname120** [comment]
@buzeak Can you try this new version? If it crashes, send me the file `ur0:/data/vitabright_log.txt`.
[vitabright-2.0b3.zip](https://github.com/devnoname120/vitabright/files/8304287/vitabright-2.0b3.zip)

**Comment by devnoname120** [comment]
@buzeak Ok here it is: [vitabright-2.0b4.zip](https://github.com/devnoname120/vitabright/files/8304412/vitabright-2.0b4.zip)

**Comment by buzeak** [comment]
@devnoname120 Ok, testing it now.

**Comment by buzeak** [comment]
@devnoname120 It WORKS!

It boots up, and the limiter blocks just the brightest two settings on those games.

I will give it a proper test now, to see if it crashes.

Should be about a hour of gaming! ![](https://github.githubassets.com/images/icons/emoji/unicode/1f601.png)

**Comment by devnoname120** [comment]
@buzeak Awesome thanks for testing! We'll just need someone with an LCD screen to confirm that these changes don't break it. I've made it such that for LCD screens it doesn't limit at all because I didn't have any reports of crashes.

**Comment by buzeak** [comment]
@devnoname120 Awesome 👍 No crashes so far, but I'm still testing.

I do not know anyone with a Vita 2000, so I can't help there.

**Comment by devnoname120** [comment]
@buzeak Great! I confirmed with 2 testers that it doesn't crash on PS Vita 2000 (LCD) either. Is there anything else I should add/improve before releasing the new version?

**Comment by buzeak** [comment]
@devnoname120 Awesome 👍. I can't think of anything else, but I do want to test if it crashes on the higher brightness setting, to see how close it is to crashing. But it seems stable at this brightness level, and I have tested it unplugged from the power supply with wifi, Bluetooth and on max valume. I just need to do a little more testing to make sure.

**Comment by devnoname120** [comment]
@buzeak OK! I'll do a release. We can always do a hotfix if needed.

**Comment by buzeak** [comment]
@devnoname120 OK, good idea.👍

**Comment by devnoname120** [comment]
@buzeak https://github.com/devnoname120/vitabright/releases ✅

**Comment by devnoname120** [comment]
@buzeak Can you check if you have the same issue as him? https://github.com/devnoname120/vitabright-lut-editor/issues/6#issue-1173808435

**Comment by buzeak** [comment]
@devnoname120 I have just tested NoPowerLimits.skprx, and it does not make it crash, it removes the limit just like it always did, and is still compatible with vitabright v2.0.

My vita is a PCH-1003

**Comment by devnoname120** [comment]
@buzeak can you send me the file `ur0:/data/vitabright_log.txt`?

**Comment by buzeak** [comment]
@devnoname120  yes, but what do you want me to test/do first exactly?

**Comment by devnoname120** [comment]
@buzeak nothing I'm just interested in seeing your OLED model. I suspect this person has a different OLED model: https://github.com/devnoname120/vitabright/issues/40

**Comment by buzeak** [comment]
@devnoname120 I'm using the latest vitabright, but there is no ur0:/data/vitabright_log.txt
My vita is a PCH-1003, but I have just read his issue and will comment on there now.

**Comment by devnoname120** [comment]
@buzeak need to use b4, logging is disabled in release builds.

**Comment by buzeak** [comment]
ok, here it is: [vitabright_log.txt](https://github.com/devnoname120/vitabright/files/8333858/vitabright_log.txt)
