### ISSUE TITLE
Not Work?

### ISSUE THREAD

**Issue by SiTWulf** [devnoname120/vitabright#9]
Hi.
Im using the Old Vita FAT with OLED and 3.65 Enso.
Trying to  down brightness above the normal minimum with not luck... and not see any difference with plugin at max or low bright slider.

Tested in Main Vita Menu.

**Comment by devnoname120** [comment]
Can you try to disable all your plugins but vitabright?
Make sure also to delete `ux0:/tai` and only use `ur0:/tai`.

**Comment by SiTWulf** [comment]
your plugin are installed in `ur0:/tai ` and not exists `ux0:/tai`

Im using GameSD to UX0 and Original Memory Card to UMA0

```
This is my config.txt
# This file is used as an alternative if ux0:tai/config.txt is not found.
# For users plugins, you must refresh taiHEN from HENkaku Settings for
# changes to take place.
# For kernel plugins, you must reboot for changes to take place.
*KERNEL
ur0:tai/gamesd_ux0.skprx
ur0:tai/nonpdrm.skprx
ur0:tai/nopsmdrm.skprx
ur0:tai/repatch.skprx
ur0:tai/vitabright.skprx
# henkaku.skprx is hard-coded to load and is not listed here
*main
ur0:tai/nolockscreen.suprx
ur0:tai/shellbat.suprx
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
```

**Comment by devnoname120** [comment]
Can you try with this configuration file?

```
This is my config.txt
*KERNEL
ur0:tai/vitabright.skprx
*main
# main is a special titleid for SceShell
ur0:tai/henkaku.suprx
*NPXS10015
# this is for modifying the version string
ur0:tai/henkaku.suprx
*NPXS10016
# this is for modifying the version string in settings widget
ur0:tai/henkaku.suprx
```

Also, make sure to use [the latest version](https://github.com/devnoname120/vitabright/releases/latest) and that you put the file `vitabright_lut.txt` from this version in `ur0:/tai`.

**Comment by SiTWulf** [comment]
I find the problem!!!

The problem is the installed Plugin.
Im using the plugin included in: [AutoPlugin](https://github.com/theheroGAC/Autoplugin) and looks outdated.

**Comment by devnoname120** [comment]
I see, thank you for reporting the issue!
